### ISSUE TITLE
Meta issue for survival analysis in tidymodels

### ISSUE THREAD

**Issue by topepo** [tidymodels/extratests#109]
Functionality/documentation

- [ ] (PR available)  tidymodels/tune#704
- [ ] tune: tidymodels/tune#706
- [ ] tune: tidymodels/tune#755
- [x] tune: tidymodels/tune#759
- [ ] tune: tidymodels/tune#762
- [ ] tune: tidymodels/tune#764
- [x] yardstick: tidymodels/yardstick#427
- [ ] censored: tidymodels/censored#267
- [ ] censored: tidymodels/censored#10
- [ ] censored: tidymodels/censored#156
- [ ] censored: tidymodels/censored#222
- [x] parsnip: tidymodels/parsnip#965
- [ ] parsnip: tidymodels/parsnip#1029
- [ ] yardstick: https://github.com/tidymodels/yardstick/issues/460

To discuss
- [ ] tidymodels/censored#147
 
Testing
- [x] https://github.com/tidymodels/parsnip/issues/1023
- [x] workflows: preprocessor https://github.com/tidymodels/extratests/pull/104/
- [x] workflows: fit interfaces #111
- [x] workflows: https://github.com/tidymodels/extratests/issues/110
- [x] yardstick: #112
- [x] tune: no tuning aka `fit_resamples()` #113
- [ ] tune: `last_fit()` #114 
- [ ] tune: `fit_best()` #115 
- [ ] tune: case weights #116 
- [x] tune: `collect_metrics()` #117 
- [ ] tune: `show_best()`, `select_best()` #118 
- [ ] tune: `augment()` #132
- [ ] workflowsets: `workflow_set()` and `workflow_map()` #119 
- [x] funetune: `tune_race_*()` tidymodels/finetune#81
- [ ] https://github.com/tidymodels/extratests/issues/146

**Comment by hfrick** [comment]
Notes on aspects to keep in mind / good things to test:
- `eval_time`: single and multiple time points, unordered, non-standard (negative, infinite)
- prediction types: `"time"` and `"survival"`
- metrics: static, dynamic, integrated, mixed
- models/engines: `proportional_hazards(engine = "glmnet")` plus some other model
- stratification: `proportional_hazards()` with engines `"glmnet"` and `"survival"` do stratification
- response: recommendation is a pre-made `Surv` object, the alternative is on-the-fly generation a la `Surv(time, status)`
